name: Deploy CDK Application

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build CDK application
      run: npm run build

    - name: Configure AWS credentials
      if: github.ref_name == 'main'
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configure AWS credentials for Dev
      if: github.ref_name == 'dev'
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Prod
      if: github.ref_name == 'main'
      env:
        CLOUDFRONT_SIGNER_PUBKEY: ${{ secrets.CLOUDFRONT_SIGNER_PUBKEY_PROD }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PHONE: ${{ secrets.ADMIN_PHONE }}
      run: npm run deploy-prod

    - name: Deploy to Dev
      if: github.ref_name != 'main'
      env:
        CLOUDFRONT_SIGNER_PUBKEY: ${{ secrets.CLOUDFRONT_SIGNER_PUBKEY_DEV }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PHONE: ${{ secrets.ADMIN_PHONE }}
      run: npm run deploy-dev